# Generated by Django 4.2.7 on 2023-11-09 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_del_Area', models.CharField(max_length=60)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Edad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Edad', models.PositiveIntegerField()),
                ('Areaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.area')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('Monto', models.FloatField()),
                ('Clienteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.cliente')),
                ('Empleadoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.empleado')),
            ],
        ),
    ]
